### ISSUE TITLE
Summarise is not working in revoscaler 

### ISSUE THREAD

**Issue by mubeenarasack** [Microsoft/microsoft-r#11]
Hi 

![untitled](https://cloud.githubusercontent.com/assets/11486584/26783322/28bdfc70-4a15-11e7-9b0a-0a3713d8b986.png)

This is the  rxdata frame that i have initially, I wants to summarise the Amount column based on TransactionId. And it is expected to be zero here. But when i executed the code below, I am always getting a nonzero value which is even greater than   .001
Result  <- data %>%
    group_by(TransactionId) %>%
    summarise(number=sum(Amount))
Result:
![result](https://cloud.githubusercontent.com/assets/11486584/26783506/374139b4-4a16-11e7-9dbe-7fed342bab50.png)

I dont know why this is happening. If anyone knows please help me?

**Comment by Hong-Revo** [comment]
This may be due to lack of precision in the underlying variable. By default xdf files store numbers as 32-bit floating point, to save space. Try the following and see what you get:

* run `rxCube(Amount ~ TransactionId, data=data)`
* convert to a dataframe and run the dplyr chain again

**Comment by Hong-Revo** [comment]
And just to clarify, if the issue is lack of precision, then calling `rxCube` or converting to a data frame will _not_ make the problem go away. You will still get a sum that is not equal to zero. But this will rule out the possibility of a bug in the dplyr chain.

**Comment by mubeenarasack** [comment]
Great.. Thanks ...You are right..this is because of lack of precision. I sorted it by converting it into integer back
