### ISSUE TITLE
MicrosoftML/Microsoft R Client for R 3.4??

### ISSUE THREAD

**Issue by wbowser** [Microsoft/microsoft-r#15]
MicrosoftML is a great package that comes with Microsoft R Client. But there is no update for R 3.4. This makes it difficult to use other packages like caret in a workflow. Is there any development version available for R 3.4 or higher?

**Comment by ramnov** [comment]
https://mran.microsoft.com/news#mro343

**Comment by RobertKomara** [comment]
3.4.3 Just released: https://www.r-bloggers.com/new-releases-microsoft-r-client-3-4-3-microsoft-ml-server-9-3/
