### ISSUE TITLE
SSH into Compute Node of Enterprise Config ARM-Template

### ISSUE THREAD

**Issue by davefrancis** [Microsoft/microsoft-r#16]
After deploying the Linux Enterprise Config ARM-Template, I am able to SSH into the Web Nodes using ports 50000, 50001, etc. How would I SSH into the Compute Nodes to install additional software?

**Comment by ramnov** [comment]
You can ssh into the compute node from one of the web nodes. Compute Node IP ranges from 10.0.1.0 - 10.0.1.255. Say one of the compute node's IP is 10.0.1.4 , run "ssh 10.0.1.4" from webnode to connect to that compute node.

**Comment by davefrancis** [comment]
Perfect, thanks for the quick reply.
