### ISSUE TITLE
Running the python ML Server package

### ISSUE THREAD

**Issue by jmagosta** [Microsoft/microsoft-r#24]
Add this instruction:

To run the python installation,  you will need to run mlserver’s python like this : 

>   /opt/microsoft/mlserver/9.2.1/bin/python/python

And then run you can import the azureml-model-management-sdk, for instance: 

>     import azureml.deploy

The actual package can be found here : 

>    /opt/microsoft/mlserver/9.2.1/runtime/python/lib/python3.5/site-packages/azureml

**Comment by ramnov** [comment]
Sure. Will add instructions in readme. 
You can also run mlserver's python using this command : 

`mlserver-python`

Source : https://docs.microsoft.com/en-us/machine-learning-server/install/machine-learning-server-linux-install
