### ISSUE TITLE
VM has reported a failure when processing extension 'customScript'

### ISSUE THREAD

**Issue by GladysEsther** [Microsoft/microsoft-r#27]
Template deployment returned the following errors:
15:15:45 - 3:11:43 PM - Resource Microsoft.Compute/virtualMachineScaleSets 'ComputeNodes' failed with message '{
15:15:45 -   "status": "Failed",
15:15:45 -   "error": {
15:15:45 -     "code": "ResourceDeploymentFailure",
15:15:45 -     "message": "The resource operation completed with terminal provisioning state 'Failed'.",
15:15:45 -     "details": [
15:15:45 -       {
15:15:45 -         "code": "VMExtensionProvisioningError",
15:15:45 -         "message": "VM has reported a failure when processing extension 'customScript'. Error message: \"Failed to download all specified files. Exiting. Error Message: The remote server returned an error: (404) Not Found.\"."
15:15:45 -       }
15:15:45 -     ]
15:15:45 -   }
15:15:45 - }'

**Comment by ramnov** [comment]
Hi @GladysEsther , which template did you deploy exactly ? Can you provide the link.

**Comment by GladysEsther** [comment]
https://github.com/Microsoft/microsoft-r/tree/master/mlserver-arm-templates/enterprise-configuration/windows-dsvm-sqlserver - Can you please help me in this ? I am working on this to get this fixed for past 2 days

**Comment by GladysEsther** [comment]
onebox and Enterprise both are providing me the same error

**Comment by ramnov** [comment]
For Command Line Deployment, variable "scriptsUri" must point to an Azure-accessible location like: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/cloudera-on-centos

`
"variables": {
  "scriptsUri": "https://raw.githubusercontent.com/Microsoft/microsoft-r/master/mlserver-arm-templates/enterprise-configuration/windows-dsvm-sqlserver/"
}
`

**Comment by GladysEsther** [comment]
Thank You Ram. This resolved one box and I am still working on Enterprise will keep you posted
