### ISSUE TITLE
Set timeout of execute

### ISSUE THREAD

**Issue by luizpaulorosaabrantes** [Microsoft/microsoft-r#28]
Hi, I've been some tests with swagger-java-client and trying to figure out how may I extend the timeout of executeCode/executeCodeAsync (SessionAPIsApi) methods. My aim is to perform a long (without response) task/routine at a remote R session, but I am getting timeout exception during the execution. 

I already tried to change it at "apiClient.setConnectTimeout(connectionTimeout)" but it seems that doesn't work at all.

Anyone already faced with that situation?
Thanks

**Comment by ramnov** [comment]
ConnectionTimeout just specifies the time to wait while trying to establish a connection before terminating the attempt and generating an error. It does not relate to execution timeout. 

For long running scripts, you can try asynchronous execution or batch execution : 

https://docs.microsoft.com/en-us/machine-learning-server/r/how-to-execute-code-remotely#asynchronous-remote-execution

https://docs.microsoft.com/en-us/machine-learning-server/operationalize/how-to-consume-web-service-asynchronously-batch

**Comment by luizpaulorosaabrantes** [comment]
I’ll try, thank you.
