### ISSUE TITLE
Problem with MicrosoftML and RevoScaleR packages in RStudio

### ISSUE THREAD

**Issue by smacc76** [Microsoft/microsoft-r#9]
Hi,

I have just installed the latest Microsoft R Client. I am using RStudio as the IDE. The MicrosoftML and RevoScaleR pacakges will not load, they do not appear in the search path, and I get the following errors on start up of RStudio:

```
Error : .onLoad failed in loadNamespace() for 'RevoScaleR', details:
  call: NULL
  error: file.exists(defaultDataDir) is not TRUE
Error : .onLoad failed in loadNamespace() for 'RevoScaleR', details:
  call: NULL
  error: file.exists(defaultDataDir) is not TRUE
In addition: Warning message:
package ‘RevoScaleR’ in options("defaultPackages") was not found 
During startup - Warning message:
package ‘MicrosoftML’ in options("defaultPackages") was not found 
[Workspace loaded from ~/.RData]
```

The regular Rgui.exe IDE has no such problems and I can run the package examples fine. Do you know what might be causing this? Can you reproduce?

Thanks.

**Comment by ramnov** [comment]
In Rstudio, can you go to Tools --> Global Options and check the R version path. It should point to C:\Program Files\Microsoft\R Client\R_SERVER

**Comment by smacc76** [comment]
Hi. I’ve discovered what it is. We are in a corporate environment so the working directory is set to a network share in the form \\machine\sharename<file:///\\machine\sharename>. RStudio does not like UNC paths in general, so I understand, and it seems these 2 packages definitely don’t like UNC paths. When I change the start up working directory to C:/ or P:/ drives RStudio opens with no error messages and the packages work fine. This post helped me understand:

https://github.com/Microsoft/RTVS/issues/3232

Thanks.
Chris.
